### ISSUE TITLE
Is there to be an update to this repo, or is discontinued

### ISSUE THREAD

**Issue by rusauth** [Eclo/SIM800h-IoT-module#2]
I get an 
Assembly: Eclo.nanoFramework.SIM800H (1.0.3.2) needs assembly 'mscorlib' (1.9.0.0)
Assembly: Eclo.nanoFramework.SIM800H (1.0.3.2) needs assembly 'Windows.Storage.Streams' (1.10.1.0)
Assembly: Eclo.nanoFramework.SIM800H (1.0.3.2) needs assembly 'System.Math' (1.3.1.0)

**Comment by josesimoes** [comment]
Since this is a companion library for our SIM800H module we are proving this library directly to our customers.
If you don't have an updated one please reach out to our support.

Thanks.

**Comment by rusauth** [comment]
Hi i have reach out to by email by didn’t get a response. Where can I acquire the module?

**Comment by josesimoes** [comment]
Apologies for the delay. I'll ping sales to get your email answered.
