### ISSUE TITLE
Unable to deploy sample to esp32

### ISSUE THREAD

**Issue by Proxicon** [Eclo/SIM800h-IoT-module#3]
Issue: Attempting to deploy SIM800HSamples to LILYGO ESP32 with SIM7600G-H appears that Eclo.nF.SIM800H have dependencies that do not function on ESP32:

using Windows.Devices.Gpio;
using Windows.Devices.SerialCommunication;

Deployment Log.

14:09:37.255 [Starting deployment transaction from v2022.2.0.41+abfe19870f]
14:09:37.260 [Starting debug engine on nanoDevice]
14:09:37.285 [Connecting to debugger engine...OK]
14:09:37.442 [The connected target does not have support for Windows.Devices.SerialCommunication.]
14:09:37.457 [Version mismatch for System.Math. Need v1.4.1.3, checksum 0xC9E0AB13.]
14:09:37.457 [The connected target has v100.0.5.4, checksum 0x46092CB1.]
14:09:37.457 [Version mismatch for nanoFramework.System.Collections. Need v1.2.0.3, checksum 0x5A31313D.]
14:09:37.457 [The connected target has v100.0.1.0, checksum 0x2DC2B090.]
14:09:37.458 [The connected target does not have support for Windows.Devices.Gpio.]
14:20:58.835 [Starting deployment transaction from v2022.2.0.41+abfe19870f]
14:20:58.836 [Starting debug engine on nanoDevice]
14:20:58.842 [Connecting to debugger engine...OK]
14:20:59.521 [Assemblies to deploy:]
14:20:59.521 [Assembly: esp_test v1.0.0.0 (336 bytes)]
14:20:59.534 [Assembly: mscorlib v1.12.0.4 (31832 bytes)]
14:20:59.549 [Deploying 2 assemblies to device]
14:21:00.186 [Incrementally deploying assemblies to the device]
14:21:00.189 [Erasing block @ 0x001B0000...]
14:21:05.816 [Deploying 0/32168 bytes.]
14:21:05.816 [Deploying 1012/32168 bytes.]
14:21:05.816 [Deploying 2024/32168 bytes.]
14:21:05.817 [Deploying 3036/32168 bytes.]
14:21:06.032 [Deploying 4048/32168 bytes.]
14:21:06.032 [Deploying 5060/32168 bytes.]
14:21:06.033 [Deploying 6072/32168 bytes.]
14:21:06.033 [Deploying 7084/32168 bytes.]
14:21:06.033 [Deploying 8096/32168 bytes.]
14:21:06.141 [Deploying 9108/32168 bytes.]
14:21:06.142 [Deploying 10120/32168 bytes.]
14:21:06.142 [Deploying 11132/32168 bytes.]
14:21:06.255 [Deploying 12144/32168 bytes.]
14:21:06.256 [Deploying 13156/32168 bytes.]
14:21:06.256 [Deploying 14168/32168 bytes.]
14:21:06.256 [Deploying 15180/32168 bytes.]
14:21:06.256 [Deploying 16192/32168 bytes.]
14:21:06.286 [Deploying 17204/32168 bytes.]
14:21:06.305 [Deploying 18216/32168 bytes.]
14:21:06.383 [Deploying 19228/32168 bytes.]
14:21:06.383 [Deploying 20240/32168 bytes.]
14:21:06.445 [Deploying 21252/32168 bytes.]
14:21:06.446 [Deploying 22264/32168 bytes.]
14:21:06.478 [Deploying 23276/32168 bytes.]
14:21:06.508 [Deploying 24288/32168 bytes.]
14:21:06.554 [Deploying 25300/32168 bytes.]
14:21:06.603 [Deploying 26312/32168 bytes.]
14:21:06.634 [Deploying 27324/32168 bytes.]
14:21:06.663 [Deploying 28336/32168 bytes.]
14:21:06.678 [Deploying 29348/32168 bytes.]
14:21:06.727 [Deploying 30360/32168 bytes.]
14:21:06.746 [Deploying 31372/32168 bytes.]
14:21:06.792 [Assemblies successfully deployed to the device]
14:21:06.811 [Launching debugger provider from v2022.2.0.41+abfe19870f]
14:21:07.123 [Attempting to connect the debugger engine (1/5)]
14:21:07.123 [Assigning debug engine of target device]
14:21:07.123 [Device running nanoCLR, updating the debug flags...]
14:21:07.685 [Attempting to connect the debugger engine (1/5)]
14:21:07.685 [Device running nanoCLR, updating the debug flags...]
14:21:08.273 [Device is running nanoCLR, requesting a restart and pause of debugger (1/5).]
14:21:08.356 [nanoCLR restarted successfully.]
14:21:08.858 [Attempting to connect the debugger engine (1/5)]
14:21:08.858 [Device running nanoCLR, updating the debug flags...]
14:21:09.447 [Device is running the CLR in initialized state]
14:21:09.447 [The debugger engine is listening to debug events from the nanoDevice target]
14:21:10.051 [Updating information about assemblies on the debugging target.]
14:21:41.086 [Starting deployment transaction from v2022.2.0.41+abfe19870f]
14:21:41.088 [Starting debug engine on nanoDevice]
14:21:41.430 [Connecting to debugger engine...OK]
14:21:41.815 [The connected target does not have support for Windows.Devices.SerialCommunication.]
14:21:41.816 [Version mismatch for System.Math. Need v1.4.1.3, checksum 0xC9E0AB13.]
14:21:41.816 [The connected target has v100.0.5.4, checksum 0x46092CB1.]
14:21:41.816 [Version mismatch for nanoFramework.System.Collections. Need v1.2.0.3, checksum 0x5A31313D.]
14:21:41.817 [The connected target has v100.0.1.0, checksum 0x2DC2B090.]
14:21:41.817 [The connected target does not have support for Windows.Devices.Gpio.]
14:53:54.034 [NanoDevices: device departure COM3]
05:19:49.222 [NanoDevices: new device arrival COM5]
05:19:49.223 [NanoDevices: candidate nano device COM5]
05:19:49.225 [NanoDevices: checking device  COM5 @ 921600]
05:19:50.232 [NanoDevices: checking device  COM5 @ 460800]
05:19:50.770 [NanoDevices: valid device ESP32_WROOM_32 @ COM5]
05:19:50.770 [NanoDevices: Serial device enumeration completed. Found 1 devices]
05:23:26.965 [Starting deployment transaction from v2022.2.0.41+abfe19870f]
05:23:26.973 [Starting debug engine on nanoDevice]
05:23:27.007 [Connecting to debugger engine...OK]
05:23:27.832 [The connected target does not have support for Windows.Devices.SerialCommunication.]
05:23:27.834 [The connected target does not have support for Windows.Devices.Gpio.]

Device capability:

System Information
HAL build info: nanoCLR running @ ESP32 built with ESP-IDF 1b16ef6
  Target:   ESP32
  Platform: ESP32

Firmware build Info:
  Date:        Oct 11 2022
  Type:        MinSizeRel build, chip rev. 3, without support for PSRAM
  CLR Version: 1.8.0.643
  Compiler:    GNU ARM GCC v8.4.0

OEM Product codes (vendor, model, SKU): 0, 0, 0

Serial Numbers (module, system):
  00000000000000000000000000000000
  0000000000000000

Target capabilities:
  Has nanoBooter: NO
  IFU capable: NO
  Has proprietary bootloader: YES

AppDomains:

Assemblies:

Native Assemblies:
  mscorlib v100.5.0.17, checksum 0x004CF1CE
  nanoFramework.Runtime.Native v100.0.9.0, checksum 0x109F6F22
  nanoFramework.Hardware.Esp32 v100.0.7.3, checksum 0xBE7FF253
  nanoFramework.Hardware.Esp32.Rmt v100.0.3.0, checksum 0x0A915860
  nanoFramework.Device.OneWire v100.0.4.0, checksum 0xB95C43B4
  nanoFramework.Networking.Sntp v100.0.4.4, checksum 0xE2D9BDED
  nanoFramework.ResourceManager v100.0.0.1, checksum 0xDCD7DF4D
  nanoFramework.System.Collections v100.0.1.0, checksum 0x2DC2B090
  nanoFramework.System.Text v100.0.0.1, checksum 0x8E6EB73D
  nanoFramework.Runtime.Events v100.0.8.0, checksum 0x0EAB00C9
  EventSink v1.0.0.0, checksum 0xF32F4C3E
  System.IO.FileSystem v1.0.0.0, checksum 0x3AB74021
  System.Math v100.0.5.4, checksum 0x46092CB1
  System.Net v100.1.5.0, checksum 0x5BAB8CB3
  System.Device.Adc v100.0.0.0, checksum 0xE5B80F0B
  System.Device.Dac v100.0.0.6, checksum 0x02B3E860
  System.Device.Gpio v100.1.0.6, checksum 0x097E7BC5
  System.Device.I2c v100.0.0.1, checksum 0xFA806D33
  System.Device.Pwm v100.1.0.4, checksum 0xABF532C3
  System.IO.Ports v100.1.6.1, checksum 0xB798CE30
  System.Device.Spi v100.1.2.0, checksum 0x3F6E2A7E
  System.Device.Wifi v100.0.6.4, checksum 0x1C1D3214
  Windows.Storage v100.0.2.0, checksum 0x954A4192

Other things tried: using Eclo.nanoFramework.SIM800H
Still have dependencies on the below that don't support esp32

using Windows.Devices.Gpio;
using Windows.Devices.SerialCommunication;

Also: Newbie C#/ASP.net dev that recently discovered nanoframework & believe it's the future! 
Any pointers to get going & use / convert the classes appreciated. Happy to contribute & submit pull request.

**Comment by antoniofagundes** [comment]
Hello @Proxicon.
For an updated version please contact our sales.

Thanks,
